config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  concern :votable do
    put    'vote' => :vote,   on: :member
    delete 'unvote' => :unvote, on: :member
  end

  resources :questions, only: [:index, :new, :create, :show], concerns: :votable do
    resources :comments, module: :questions

    resources :answers, only: [:create], concerns: :votable do
      resources :comments, module: :answers
    end
  end

  devise_for :users
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer
#  user_id     :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes, as: :votable
  has_many :comments, as: :commentable

  validates :description, presence: true

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  user_id          :integer
#  commentable_id   :integer
#  commentable_type :string
#  body             :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :user, :body, presence: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable
  has_many :comments, as: :commentable

  validates :title, :description, presence: true

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  votable_id   :integer
#  votable_type :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  def create
    answer = Answer.find(params[:answer_id])
    @answer_comment = answer.comments.new(comment_params)
    @answer_comment.user = current_user
    if @answer_comment.save
      redirect_to answer.question
    else
      @question = answer.question
      render 'questions/show'
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Votable

  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    if @answer.save
      redirect_to @question, notice: "Tu respuesta ha sido creada con éxito"
    else
      @question.answers.reset # removes the invalid answer by reloading from DB
      render 'questions/show'
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
# base class for Questions::CommentsController and Answers::CommentsController
class CommentsController < ApplicationController
  before_action :authenticate_user!

  private
    def comment_params
      params.require(:comment).permit(:body).merge(user: current_user)
    end
end

app/controllers/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern
  
  def vote
    votable.votes.create(user: current_user)
    redirect_to question_path
  end

  def unvote
    votable.votes.where(user: current_user).take.try(:destroy)
    redirect_to question_path
  end

  def votable
    @votable ||= controller_name.classify.constantize.find(params[:id])
  end

  def question_path
    votable.respond_to?(:question) ? @votable.question : @votable
  end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  def create
    @question = Question.find(params[:question_id])
    @question_comment = @question.comments.new(comment_params)
    @question_comment.user = current_user
    if @question_comment.save
      redirect_to @question
    else
      render 'questions/show'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Votable

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.all.order('created_at DESC')
    if params[:q]
      @questions = @questions.where('title like ?', "%#{params[:q]}%")
    end
  end

  def new
    @question = Question.new    
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to questions_path, notice: "La pregunta se ha publicado con éxito"
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  private
    def question_params
      params.require(:question).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HtmlWithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer: language)
      end
    end
  end

  def markdown(text)
    renderer = HtmlWithPygments.new(hard_wrap: true, filter_html: false)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

  def bootstrap_class_for(flash_type)
    flash_types = { success: "alert-success",
                    error: "alert-danger",
                    alert: "alert-warning",
                    notice: "alert-info" }
    flash_types[flash_type.to_sym] || alert-block
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <ul>#{messages}</ul>
    </DIV>
    HTML

    html.html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flowoverstack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Flow<strong>overstack</strong></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
        <%= form_tag questions_path, method: :get, class: "navbar-form navbar-right" do %>
          <div class="form-group">
            <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "Search" %>
          </div>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Ingresar", new_user_session_path %></li>
            <li><%= link_to "Registrarse", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" style="margin-top: -20px;">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/questions/_comments.html.erb
<% commentable.comments.each do |comment| %>
  <div class="comment">
    <%= comment.body %>
  </div>
<% end %>

app/views/questions/_errors.html.erb
<% if resource && resource.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="container questions-page">
  <div class="row">
    <div class="col-sm-12">
      <h1>Preguntas</h1>

      <div class="text-right">
        <%= link_to "Hacer una Pregunta", new_question_path, class: "btn btn-primary" %>
      </div>

      <table class="table questions-list">
        <tbody>
          <% @questions.each do |question| %>
            <tr>
              <td class="metric">
                <span class="metric-value"><%= question.votes.count %></span>
                <span class="metric-label">Votos</span>
              </td>
              <td class="metric">
                <span class="metric-value"><%= question.answers.count %></span>
                <span class="metric-label">Respuestas</span>
              </td>
              <td class="question-info">
                <span class="question-title"><%= link_to question.title, question %></span>
                <span class="question-details">Preguntó <%= question.user.email %> hace <%= distance_of_time_in_words(question.created_at, Date.current) %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2>Publicar Pregunta</h2>

      <% if @question.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @question do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Título" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, rows: 7, class: "form-control input-lg", placeholder: "Descripción" %>
        </div>

        <div>
          <%= f.submit "¡Preguntar!", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container question-page">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h2><%= @question.title %></h2>
      <div class="qa-description">
        <div class="qa-votes">
          <% if @question.voted_by? current_user %>
            <%= link_to vote_question_path(@question), class: "qa-upvote upvote-active", method: :delete do %>
              <span class="upvote-arrow"></span>
              <span class="upvote-count"><%= @question.votes.count %></span>
            <% end %>
          <% else %>
            <%= link_to vote_question_path(@question), class: "qa-upvote", method: :put do %>
              <span class="upvote-arrow"></span>
              <span class="upvote-count"><%= @question.votes.count %></span>
            <% end %>
          <% end %>
        </div>
        <div class="body"><%= markdown @question.description %></div>
      </div>
      <div class="qa-comments">
        <%= render 'questions/comments', commentable: @question %>

        <div class="new-qa-comment">
          <%= render 'questions/errors', resource: @question_comment %>
          <%= form_for [@question, Comment.new] do |f| %>
            <div class="form-group">
              <%= f.text_area :body, class: "form-control", placeholder: "Agrega un comentario" %>
            </div>
            <div class="text-right">
              <%= f.submit "Comentar", class: "btn btn-primary btn-sm" %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="answers">
        <h3><%= @question.answers.length %> Respuesta(s)</h3>

        <% if @question.answers.length == 0 %>
          <p class="no-answer">Si conoces alguien que pueda responder esta preguntar por favor tímbrale y dile que lo necesitamos con urgencia.</p>
        <% end %>

        <% @question.answers.each do |answer| %>
          <div class="answer qa-description">
            <div class="body"><%= markdown answer.description %></div>
          </div>

          <div class="qa-comments">
            <%= render 'questions/comments', commentable: answer %>

            <% puts answer.inspect %>
            <div class="new-qa-comment">
              <%= render 'questions/errors', resource: @answer_comment %>
              <%= form_for [@question, answer, Comment.new] do |f| %>
                <div class="form-group">
                  <%= f.text_area :body, class: "form-control", placeholder: "Agrega un comentario" %>
                </div>
                <div class="text-right">
                  <%= f.submit "Comentar", class: "btn btn-primary btn-sm" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if signed_in? %>
          <div class="new-answer">
            <h3>Tu Respuesta</h3>
            <%= render 'questions/errors', resource: @answer %>
            <%= form_for [@question, @question.answers.new] do |f| %>
              <div class="form-group">
                <%= f.text_area :description, rows: 5, class: "form-control input-lg" %>
              </div>
              <div class="text-right">
                <%= f.submit "Enviar Respuesta", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>